#!/bin/bash
# Submitted at: $(date +%Y-%m-%d\ %H:%M:%S)
#SBATCH --chdir /home/jsyu/ManipTrans
#SBATCH --nodes 1
#SBATCH --cpus-per-task 8
#SBATCH --ntasks 1
#SBATCH --mem 40G
#SBATCH --gres=gpu:1
#SBATCH --qos=normal
#SBATCH --output=logs/inspire/slurm_%j/slurm-%j.out
#SBATCH --error=logs/inspire/slurm_%j/slurm-%j.err
#SBATCH --mail-user=jeffrey.yu@epfl.ch
#SBATCH --mail-type=END,FAIL
#SBATCH --time 72:00:00

echo "Starting ManipTrans inspire training on $HOSTNAME at $(date)"
source /home/jsyu/miniconda/etc/profile.d/conda.sh
conda activate maniptrans

DATA_INDICES="3b1e6@12,d6fe3@0,8e5df@13,a78a0@1,0f900@10,b5fa3@10,f7d37@18,85abe@4,e49f5@0"
EXPERIMENT_NAME="capping_alcohol_burner"

python main/rl/train.py \
    task=ResDexHand \
    dexhand=inspire \
    side=BiH \
    headless=true \
    num_envs=8192 \
    learning_rate=2e-4 \
    test=false \
    randomStateInit=true \
    "dataIndices=[${DATA_INDICES}]" \
    rh_base_model_checkpoint=assets/imitator_rh_inspire.pth \
    lh_base_model_checkpoint=assets/imitator_lh_inspire.pth \
    early_stop_epochs=1000 \
    actionsMovingAverage=0.6 \
    max_iterations=10000 \
    wandb_activate=True \
    wandb_entity=jeffreyyu880-epfl \
    wandb_project=ManipTrans \
    useCoaxialReward=false \
    useTrajAug=true \
    numTrajAug=20 \
    jointNoiseCm=0.5 \
    maxDemoLength=252 \
    "experiment='${EXPERIMENT_NAME}_9demos_maxlen252_traj_aug_noise'"
