#!/bin/bash
# Submitted at: $(date +%Y-%m-%d\ %H:%M:%S)
#SBATCH --chdir /home/jsyu/ManipTrans
#SBATCH --nodes 1
#SBATCH --cpus-per-task 8
#SBATCH --ntasks 1
#SBATCH --mem 40G
#SBATCH --gres=gpu:1
#SBATCH --qos=normal
#SBATCH --output=logs/inspire/slurm_%j/slurm-%j.out
#SBATCH --error=logs/inspire/slurm_%j/slurm-%j.err
#SBATCH --mail-user=jeffrey.yu@epfl.ch
#SBATCH --mail-type=END,FAIL
#SBATCH --time 72:00:00

echo "Starting ManipTrans inspire training on $HOSTNAME at $(date)"
source /home/jsyu/miniconda/etc/profile.d/conda.sh
conda activate maniptrans

DATA_INDICES="751fb@16"
EXPERIMENT_NAME="capping_alcohol_burner"

python main/rl/train.py \
    task=ResDexHand \
    dexhand=inspire \
    side=BiH \
    headless=true \
    num_envs=8192 \
    learning_rate=2e-4 \
    test=false \
    randomStateInit=true \
    "dataIndices=[${DATA_INDICES}]" \
    rh_base_model_checkpoint=assets/imitator_rh_inspire.pth \
    lh_base_model_checkpoint=assets/imitator_lh_inspire.pth \
    early_stop_epochs=1000 \
    actionsMovingAverage=0.6 \
    max_iterations=10000 \
    wandb_activate=True \
    wandb_entity=jeffreyyu880-epfl \
    wandb_project=ManipTrans \
    useCoaxialReward=false \
    useTrajAug=true \
    numTrajAug=20 \
    "experiment='${EXPERIMENT_NAME}_751fb@16_augment_traj'"

# experiment is the wandb run name

# pen capping demos
# 2d54f@3
# 8a043@3
# 9a028@13
# 380a3@3
# 82851@13
# e6d2b@3
# e9aab@2
# fbc74@2