#!/bin/bash
# Submitted at: $(date +%Y-%m-%d\ %H:%M:%S)
#SBATCH --chdir /home/jsyu/ManipTrans
#SBATCH --nodes 1
#SBATCH --cpus-per-task 8
#SBATCH --ntasks 1
#SBATCH --mem 40G
#SBATCH --gres=gpu:1
#SBATCH --qos=normal
#SBATCH --output=logs/inspire/slurm_%j/slurm-%j.out
#SBATCH --error=logs/inspire/slurm_%j/slurm-%j.err
#SBATCH --mail-user=jeffrey.yu@epfl.ch
#SBATCH --mail-type=END,FAIL
#SBATCH --time 72:00:00

echo "Starting ManipTrans inspire training on $HOSTNAME at $(date)"
source /home/jsyu/miniconda/etc/profile.d/conda.sh
conda activate maniptrans

# DATA_INDICES="3b1e6@12,d6fe3@0,8e5df@13,a78a0@1,0f900@10,f7d37@18,85abe@4,e49f5@0"
# DATA_INDICES="m_161551,m_170401,m_170527,m_170654,m_170753"
DATA_INDICES="m_161551,m_161610,m_163932,m_170401,m_170418,m_170435,m_170527,m_170541,m_170612,m_170654,m_164331,m_164346,m_170753,m_170805,m_164533"
# DATA_INDICES="m_131404,m_131434,m_131227,m_131256"
EXPERIMENT_NAME="dist_1-5_AUG_LIMITED"

python main/rl/train.py \
    task=ResDexHand \
    dexhand=inspire \
    side=BiH \
    headless=true \
    num_envs=8192 \
    learning_rate=2e-4 \
    test=false \
    randomStateInit=true \
    "dataIndices=[${DATA_INDICES}]" \
    rh_base_model_checkpoint=assets/imitator_rh_inspire.pth \
    lh_base_model_checkpoint=assets/imitator_lh_inspire.pth \
    early_stop_epochs=1000 \
    actionsMovingAverage=0.6 \
    max_iterations=10000 \
    wandb_activate=True \
    wandb_entity=jeffreyyu880-epfl \
    wandb_project=ManipTrans \
    useCoaxialReward=false \
    useTrajAug=true \
    RH_LH_Table_Center_Aug=true \
    RH_LObj_Center_Aug=true \
    RH_RObj_Center_Aug=true \
    LH_LObj_Center_Aug=true \
    causal=true \
    jointNoiseCm=0.0 \
    failureThresholdNoiseCompensation=1.5 \
    numTrajAug=100 \
    "experiment='${EXPERIMENT_NAME}'"

# you NEED useTrajAug in order to create augmented trajectories, if RH_LObj_Center_Aug=false, then it uses the rotation about the center of the table

# failureThresholdNoiseCompensation MULTIPLIES the failure threshold, which increases the window of varying from the joint positions from the noise 
# run with jointnoise: jointNoiseCm=0.5
# useTrajAug is backwards compatible, if only it is true, it performs TableCenterAug